image: golang:1.12-stretch

stages:
  - test
  - build

before_script:
  - make mod

test:
  stage: test
  image: golang:1.12-stretch
  script:
    - make test

build:
  stage: build
  image: golang:1.12-stretch
  script:
    - make build
  only:
    - master
